<?php

function _iby_bodies_access() {
  return user_is_logged_in();
}

/**
 * Implements hook_menu().
 */
function iby_bodies_menu() { 
  $items = array();
  
  $items['iby_bodies'] = array(
    'title' => 'IBY Bodies',
    'page callback' => '_iby_bodies_page',
    'access callback' => '_iby_bodies_access',
    'type' => MENU_CALLBACK
  );
  
  return $items;
}

/**
 * Implementation of hook_theme().
 */
function iby_bodies_theme() {
  $themes = array();
  $themes['iby_bodies_page'] = array(
    'variables' => array(),
  );
//  $themes['iby_bodies_form'] = array(
//    'render element' => 'form',
//    'template' => 'iby-bodies-form',
//  );
  return $themes;
}

function _iby_bodies_page() {
  drupal_set_title(t('images in bodies'));
  $output = theme('iby_bodies_page', array());
  return $output;
}

//function iby_bodies_form($form, &$form_state) {
//  $terms_url = variable_get('iby_bodies_terms_url', 'legal');
//  $options['attributes'] = array('class' => "sq-ajax-textpage-link");
//  $options['query'] = array('show_ajax' => 1);
//  $form['mail'] = array(
//    '#type' => 'textfield',
//    '#title' => t('E-mail address'),
//    '#maxlength' => EMAIL_MAX_LENGTH,
//    '#description' => t('You use this email for logging in. We do not mis-use your e-mail bla bla bla.'),    
//    '#required' => TRUE
//  );
//  $form['check'] = array(
//    '#type' => 'checkbox',
//    '#title' => t('I have read the !link', array('!link' => l(t('terms and conditions'), $terms_url, $options))),
//    '#required' => TRUE
//  );
//  $form['field_newsletters'] = array(
//    '#type' => 'checkbox',
//    '#attributes' => array('checked' => 'checked'),
//    '#title' => t('I wish to receive monthly newsletters to keep me up-to-date on what’s happening in this community.'),
//  );
//  $form['submit'] = array(
//    '#type' => 'submit',
//    '#value' => t('Send')
//  );
//  return $form;
//}

//function iby_bodies_form_validate($form, &$form_state) { 
//  $mail = trim($form_state['values']['mail']);
//  // Try to load by email.
//  $users = user_load_multiple(array(), array('mail' => $mail, 'status' => '1'));
//  $account = reset($users);  
//  if (isset($account->uid)) {
//    form_set_value(array('#parents' => array('account')), $account, $form_state);
//  }
//  else {
//    if (!empty($mail)) {
//      form_set_error('name', t('Sorry, %name is not recognized as a user name or an e-mail address.', array('%name' => $mail)));
//    }
//  }
//}

//function iby_bodies_form_submit($form, &$form_state) { 
//  module_load_include('inc', 'user', 'user.pages');
//  user_pass_submit($form, $form_state);
//}

//function iby_bodies_form_iby_bodies_form_alter(&$form) {
//  $form['#submit'][] = 'iby_bodies_form_iby_bodies_form_submit';
//}

//function iby_bodies_form_iby_bodies_form_submit(&$form, &$form_state) {
//  $form_state['redirect'] = 'user/forgot';
//}




function theme_iby_bodies_page($variables) {
  $output = '';


set_time_limit(900);


//$qwe = node_load(19801);
//$body = _process_inline_images($qwe->body['und'][0]['value']);
//$qwe->body['und'][0]['value'] = $body;
//node_save($qwe);

//$cts = array( 'article', 'blog', 'dashboard_slide', 'forum', 'important_notice', 'page', 'webform',);
$cts = array('forum', 'page');

//foreach ($cts as $ct) {
//  $nids = db_select('field_data_body', 'n')
//    ->fields('n', array('entity_id'))
//    ->condition('n.bundle', $ct)
//    ->execute()
//    ->fetchCol(); // returns an indexed array
//  $count_nids = count($nids);
//error_log(print_r("\n",1),3,'/home/asd/qwe.log');
//error_log(print_r('count of "' . $ct . '": ' . $count_nids,1),3,'/home/asd/qwe.log');
//error_log(print_r("\n",1),3,'/home/asd/qwe.log');
//  $curr = 0;
//  foreach ($nids as $nid) {
//    $curr += 1;
//    $node = node_load($nid);
//    $body_text = _process_inline_images($node->body['und'][0]['value']);
//    $node->body['und'][0]['value'] = $body_text;
//    node_save($node);
//    if ((($count_nids - $curr) % 100) == 0) {
//error_log(print_r($curr,1),3,'/home/asd/qwe.log');
//error_log(print_r("\n",1),3,'/home/asd/qwe.log');
//    }
//  }
//}


//$qwe = comment_load(35088);
//$comm = _process_inline_images($qwe->comment_body['und'][0]['value']);
////error_log(print_r($comm,1),3,'/home/asd/qwe.log');
//$qwe->comment_body['und'][0]['value'] = $comm;
//comment_submit($qwe);
//comment_save($qwe);

$cids = db_select('field_data_comment_body', 'n')
  ->fields('n', array('entity_id'))
  ->condition('n.bundle', 'comment_node_forum')
  ->execute()
  ->fetchCol(); // returns an indexed array
$count_cids = count($cids);
error_log(print_r("\n",1),3,'/home/asd/qwe.log');
error_log(print_r('count of "comments": ' . $count_cids,1),3,'/home/asd/qwe.log');
error_log(print_r("\n",1),3,'/home/asd/qwe.log');
$curr = 0;
foreach ($cids as $cid) {
  $curr += 1;
  $comm = comment_load($cid);
  $body_text = _process_inline_images($comm->comment_body['und'][0]['value']);
  $comm->comment_body['und'][0]['value'] = $body_text;
  comment_submit($comm);
  comment_save($comm);
  if ((($count_cids - $curr) % 100) == 0) {
error_log(print_r($curr,1),3,'/home/asd/qwe.log');
error_log(print_r("\n",1),3,'/home/asd/qwe.log');
  }
}



//$pids = db_select('pm_message', 'p')
//  ->fields('p', array('mid'))
//  ->execute()
//  ->fetchCol(); // returns an indexed array
//$output .= '<br> <br> count of "private": ' . count($pids);
//privatemsg_message_load($pmid);
//privatemsg_message_change_delete($pmid, FALSE);



//  $form = drupal_get_form('iby_bodies_form');
//  $output = drupal_render($form);

//  $output .= '<div class="request-new-password">';
//  $output .= '<p>If you have trouble signing in or have changed your e-mail address, then please visit</p>';
//  $output .= '<p><a href="/node/17331">Request a new password</a></p>';
//  $output .= '</div>';

  return $output;
}

/**
 * Perform modifications of inline images` paths.
 */
function _process_inline_images($body, $dest_uid = NULL) {

  $public_path = file_create_url('public://');

  $imgtags = array();
  $preg_result = preg_match_all('/<img[^>]+>/i', $body, $imgtags, PREG_SET_ORDER);
  if ($preg_result != 0 OR $preg_result != FALSE) {
    foreach ($imgtags as $tag) {

      preg_match('/src=[\s]?"([^"]*)"/i',$tag[0], $img);

      // == img tag should be removed --\
      /*
        forum_images/
        system/files/
        src=""
        src="data:image/ //- maybe shouldnt be removed, images hardcodedd into bodies
        <img /> == no src at all
        src="/sites/default/files/forum/forum_images/back_to_top.png"
        src="/sites/default/files/forum/upl"
      */
      // == img tag should be removed --/

      if (
        (isset($img[1]) AND $img[1] == '') // src=""
        OR
        ($img == array()) // no src at all
        OR
        (strpos($img[1], 'forum_images/') !== false)
        OR
        (strpos($img[1], 'system/files/') !== false)
        OR
        (strpos($tag[0], 'src="/sites/default/files/forum/forum_images/back_to_top.png"') !== false)
        OR
        (strpos($tag[0], 'src="/sites/default/files/forum/upl"') !== false)

        //- maybe shouldnt be removed, images hardcodedd into bodies
        //OR
        //(strpos($img[1], 'data:image/') !== false)
      ) {
        // Just remove crippled tags or tags with not used images.
        $body = str_replace($tag, '', $body);
        continue;
      }


//      // ==  smileys search patterns --\
//      /*
//        smileys/
//        emotions/
//       */
//      // ==  smileys search patterns --/
//
//      if (
//        (strpos($img[1], 'smileys/') !== false)
//        OR
//        (strpos($img[1], 'emotions/') !== false)
//      ) {
//        // ! FOR NOW just remove smiles !
//        $body = str_replace($tag, '', $body);
//        continue;
//      }


      // ==  images search patterns --\
      /*


        innovationbyyou.com/sites/default/files
3 - page
201 - forum
269 - comments
  11 - pmsg


        sites/default/files/http:__
no entrys


+        sites/default/files/http://
16 - forum
8 - comments
0 - pmsg


+        sites/default/files/forum//sites/default/files/forum/uploads
4 - forum
0 - comments
0 - pmsg


+        innovationbyyou.com/sites/default/files/forum/uploads
0 - forum
2 - comments
0 - pmsg


-        sites/default/files/forum/uploads
378 - forum
197 - comments
  35525 - problematic comment
0 - pmsg


+        /sites/default/files/forum//sites/default/files/forum/smileys
? - forum
33 - comments
0 - pmsg


        /sites/default/files/forum/smileys
//SELECT entity_id, comment_body_value
//FROM `ibytopeytz`.`field_data_comment_body`
//WHERE comment_body_value LIKE '%%/sites/default/files/forum/smileys%%'
//17 items problematic ??
? - forum
1696 - comments
0 - pmsg


//        forum/uploads
//380 - forum
//198 - comments


        sites/default/files
//SELECT entity_id, comment_body_value
//FROM `ibytopeytz`.`field_data_comment_body`
//WHERE comment_body_value LIKE '%%sites/default/files%%'
//23 items problematic ??

      */
      // ==  images search patterns --/

      if (
        (strpos($img[1], 'http://www.stoma-innovation.com/forum/uploads') !== false)
      OR
        (strpos($img[1], 'http://www.iasupport.org/forum/uploads') !== false)
      ) {
        // just pass some external images with 'forum/upload' in src
        continue;
      }

      if (strpos($img[1], 'innovationbyyou.com/sites/default/files') !== false) {
        $file = explode('sites/default/files/', $img[1]);
        $new_src = $public_path . $file[1];
        $body = str_replace($img[1], $new_src, $body);
        continue;
      }

      if (strpos($img[1], 'sites/default/files/http:__') !== false) {
        // NO ENTRYS, SO ALL THIS PART COMMENTED
        //$file = explode('sites/default/files', $img[1]);
        //$new_src = trim(array_pop($file), '/');
        //$new_src = array_pop($file);
        //$body = str_replace($img[1], $new_src, $body);
        //continue;
      }

      if (strpos($img[1], 'sites/default/files/http://') !== false) {
        $file = explode('sites/default/files/', $img[1]);
        $body = str_replace($img[1], $file[1], $body);
        continue;
      }

      if (strpos($img[1], 'sites/default/files/forum//sites/default/files/forum/uploads') !== false) {
        $file = explode('//', $img[1]);
        $new_src = '/' . $file[1];
        $file = explode('sites/default/files/', $file[1]);
        $new_src = $public_path . $file[1];
        $body = str_replace($img[1], $new_src, $body);
        continue;
      }

      if (strpos($img[1], 'sites/default/files/forum/uploads') !== false) {
        $file = explode('sites/default/files/', $img[1]);
        $new_src = $public_path . $file[1];
        $body = str_replace($img[1], $new_src, $body);
        continue;
      }

      if (strpos($img[1], '/sites/default/files/forum//sites/default/files/forum/smileys') !== false) {
        $file = explode('//', $img[1]);
        $new_src = '/' . $file[1];
        $file = explode('sites/default/files/', $file[1]);
        $new_src = $public_path . $file[1];
        $body = str_replace($img[1], $new_src, $body);
        continue;
      }

      if (strpos($img[1], '/sites/default/files/forum/smileys') !== false) {
        $file = explode('sites/default/files/', $img[1]);
        $new_src = $public_path . $file[1];
        $body = str_replace($img[1], $new_src, $body);
        continue;
      }


//      if (strpos($img[1], 'forum/uploads') !== false) {
//        $file = explode('/', $img[1]);
//        $filename = array_pop($file);
//        $filename_raw = rawurldecode(html_entity_decode($filename));
//
//        $source_path_file = IBY_MIGRATE_FILES . str_replace('/sites/default/files', '', $img[1]);
//        $source_path_file_raw = rawurldecode(html_entity_decode($source_path_file));
//        $source_path_xml = str_replace($filename, 'folder_info.xml', $source_path_file);
//        $source_path_xml_raw = rawurldecode(html_entity_decode($source_path_xml));
//
//        $xmlstr = file_get_contents($source_path_xml_raw);
//        $xmlobj = simplexml_load_string($xmlstr, NULL, LIBXML_NOCDATA);
//        $owner = get_object_vars($xmlobj->owner);
//        $owner_uid = $owner['uid'];
//
//        if (file_exists($source_path_file_raw)) {
//          // php 5.3 and above version
//          //$finfo = new finfo(FILEINFO_MIME);
//          //$info = $finfo->file($source_path_file_raw);
//          //$mime = substr($info, 0, strpos($info, ';'));
//
//          // php lower than 5.3 version
//          $info = mime_content_type($source_path_file_raw);
//
//          $type = substr($info, 0, strpos($info, '/'));
//          $size = filesize($source_path_file_raw);
//
//          $file_data = file_get_contents($source_path_file_raw);
//          $new_file = file_save_data($file_data, 'public://' . $filename_raw, FILE_EXISTS_REPLACE);
//          $new_file->uid = $dest_uid;
//          $new_file->type = $type;
//          file_save($new_file);
//          file_usage_add($new_file, 'user', 'user', $dest_uid);
//        }
//
//        $mediatag = mediatag_by_filename($filename_raw);
//        $body = str_replace($tag, $mediatag, $body);
//        continue;
//      }

//      if (strpos($img[1], 'sites/default/files') !== false) {
//        $file = explode('/', $img[1]);
//        $filename = rawurldecode(array_pop($file));
//        $mediatag = mediatag_by_filename($filename);
//        $body = str_replace($tag, $mediatag, $body);
//        continue;
//      }

    }

  }

  return $body;

}
